---
title: "Curso R: Introducción al procesamiento, visualización y mapeo de datos espaciales"

output: html_document
---

<a href="R_curso_SCMas.html">Día 1</a>
<a href="R_curso_SCMas_dia2.html">Día 2</a>
<a href="Datos_Curso_R_SCMas.zip">Datos</a>

## Objetivo

El objetivo de este curso es proporcionar capacitación en el procesamiento, visualización y mapeo de  datos espaciales utilizando R. El curso se centra en un pequeño conjunto de paquetes populares para  estas tareas, muchos de los cuales se extraen de una colección de paquetes denominada tidyverse.  Mediante  el  uso  de  un  estudio  de  caso  con  mamíferos  neotropicales,  los  participantes  de  este  aprenderán  herramientas  básicas  sobre  cómo  convertir  fácilmente  sus  datos  en  un  formato  "ordenado", lo que facilita la verificación y el análisis de errores. También crearemos algunos gráficos  para resumir los datos y exploraremos opciones para la generación de mapas. 

## Estructura del curso 
 
Los principales paquetes que se utilizarán se presentan entre paréntesis. 
 
### Día 1 #####
 
Introducción al análisis de datos en R. Tipos de objetos en R. 
Visualización para comprobar errores y patrones en los datos (ggplot) 
Preparación de tablas para la generación de análisis espaciales (dplyr – tidyr) 
 
### Día 2 #### 
 
Importación y visualización de datos espaciales (sf, raster, rgdal). 
Generación de mapas (raster, ggmap, leaflet) 


## Datos 

Los datos requridos para completar el curso pueden ser descargados de la carpeta Datos_Curso_R_SCMas.zip
 
## Requisitos
 
Computador con acceso a internet y R y RStudio previamente instalados. La instalación del programa 
no se explicará durante el curso.  
 
La experiencia requerida en R es mínima, sin embargo, se espera que los participantes estén 
familiarizados con el siguiente tipo de objetos básicos R: vectores, listas y dataframes. 
https://rpubs.com/joser/objetos  
 
Para el segundo día, un conocimiento básico sobre conceptos relacionados con sistemas de 
coordenadas y proyecciones geográficas será ventajoso, aunque no esencial.  

## Instructores  
 
Dr. Felipe Suárez-Castro. Universidad de Griffith, Australia – Sociedad Colombiana de Mastozoología  
Dr. Diego Lizcano. Sociedad Colombiana de Mastozoología 
Contacto: felipesuarezca@gmail.com  

## Créditos

Algunos ejercicios presentados en este curso están adaptados del excelente curso desarrollado por C.J. Brown, D. Schoeman, A.J. Richardson y B. Venables, el cual se encuentra disponible en:

https://www.seascapemodels.org/code.html
